name: Mobile Tests CI

on:
  push:
    branches:
      - ci

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: ENVIRONMENT=saucelabs npm run test:smoke